services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo-data: